export const data = [
  {
    id: 1,
    name: "John Doe",
    designation: "Software Engineer",
    isSelected: false,
    organization: "Tech Corp",
  },
  {
    id: 2,
    name: "Jane Smith",
    designation: "Product Manager",
    isSelected: false,
    organization: "Innovate Ltd",
  },
  {
    id: 3,
    name: "Alice Johnson",
    designation: "UI/UX Designer",
    isSelected: false,
    organization: "Creative Solutions",
  },
  {
    id: 4,
    name: "Bob Brown",
    designation: "Data Scientist",
    isSelected: false,
    organization: "Data Insights",
  },
  {
    id: 5,
    name: "Charlie Green",
    designation: "DevOps Engineer",
    isSelected: false,
    organization: "Cloud Masters",
  },
  {
    id: 6,
    name: "Diana White",
    designation: "QA Tester",
    isSelected: false,
    organization: "Quality Checkers",
  },
  {
    id: 7,
    name: "Eve Black",
    designation: "HR Manager",
    isSelected: false,
    organization: "People First",
  },
  {
    id: 8,
    name: "Frank Blue",
    designation: "Marketing Specialist",
    isSelected: false,
    organization: "Market Leaders",
  },
  {
    id: 9,
    name: "Grace Gray",
    designation: "Financial Analyst",
    isSelected: false,
    organization: "Finance Gurus",
  },
  {
    id: 10,
    name: "Henry Red",
    designation: "Operations Manager",
    isSelected: false,
    organization: "Ops Experts",
  },
];
